---
title: Quotes
---

Gathering qoutes that I come across 

## 2025
- Funny thing about getting older your eyesight starts to get weaker but your ability to see through people's bullshit gets better. - `Anonymous`
- Agents are not only going to change how everyone interacts with computers. They’re also going to upend the software industry, bringing about the biggest revolution in computing since we went from typing commands to tapping on icons. - `Bill Gates, Co-founder of Microsoft`
- Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – `Martin Fowler`
- In all chaos there is a cosmos, in all disorder a secret order. – `Carl Jung`



## 2024
- When you focus on you, you grow. When you focus on shit, shit grows - `Dwayne Johnson`
- People do not decide their futures, they decide their habits and their habits decide their futures - `F. M. Alexander`
- Watch your thoughts, they become your words; watch your words, they become your actions; watch your actions, they become your habits; watch your habits, they become your character; watch your character, it becomes your destiny. - `Lao Tzu`
- Travel and tell no one, live a true love story and tell no one, live happily and tell no one, people ruin beautiful things. - `Kahlil Gibran`
- If you spend your time chasing butterflies, they'll fly away. But if you spend your time making a beautiful garden, the butterflies will come. Don't chase, attract. - `Japanese proverb`
- It is impossible for a man to learn what he thinks he already knows. - `Epictetus`
- work is fun and fun is work
- When you start taking care of yourself, you start feeling better, you start looking better, and you even start to attract better. It all starts with you. - `Anonymous`
- It may seem difficult at first, but everything is difficult at first. -  `Miyamoto Musashi`
- Everything we hear is an opinion not a fact, everything we see is a perspective not the truth. - `Marcus Aurelius`
- Master the mind or you will be a slave to your thoughts
- Train your mind. Train your body. Trust in the force - `Asoka Tano`
- You earn a living to Live Well not to kill yourself with stress - `Sadhguru`
- When words become unclear, I shall focus with photographs. When images become inadequate, I shall be content with silence. - `Ansel Adams`
- The happiness of your life depends on the quality of your thought - `Marcus Aurelius`
- Death is sinking into slumbers deep. Birth again is waking out of sleep - `Thirukkural`
- The gap between your current life and the life you want is called Focus - `Anonymous`
- Every positive thought has a negative thought associated with it. - `Anonymous`
- Desire to learn is incredibly scarce in this world. `Naval Revikant`
- Discipline is choosing between what you want now and what you want most - `Abraham Lincoln`
- What get measured get managed
- Behaviour is always greater than knowledge. Because in life there are many situations where knowledge fails but Behaviour can still handle - `A.P.J. Abdul Kalam`
- We live in the time of cutting edge obsolescence - `John Finger`
- The idea of progress is built on the notion that if we admit our ignorance and invest resources in research, things can improve. - `Yuval Noah Harari`
	- the progress depends on recognizing our lack of knowledge and actively investing in research to address it. By acknowledging what we do not know and dedicating resources to learn and innovate, we can achieve improvements and advancements.
- Edison did not look for problems in need for solutions; he looked for solutions in need for modifications - `The New Yorker`
- The man who blames other has a long journey ahead, the man who blames himelf is halfway there, and the man who blames no one has already arived - `Chineese proverb`
- If you don't ask the right questions, you don't get the right answers. - `Robert Half`
- Worrying doesn't take away tomorrow's troubles. It takes away today's peace. - `Annonymous`
- I have come to believe that the whole world is an enigma ... a harmless enigma that is made terrible by our own mad attempt to interrupt as though it had an underlying truth. - `Umberto Eco`
- Life is too short to hangout with people who aren't resourceful. - `Jeff Bezos`
- The prompt is the fundamental unit of knowledge work. - `@IndyDevDan`



