# My Publications

---


## 2024

- Identifying and Optimizing Critical Process Parameters for Large-Scale Manufacturing of iPSC Derived Insulin-Producing β-cells [external_link](https://doi.org/10.21203/rs.3.rs-4244002/v1)

- Addressing bioreactor hiPSC aggregate stability, maintenance and scaleup challenges using a design of experiment approach [pubmed](https://pubmed.ncbi.nlm.nih.gov/38956608/)

## 2023

- Microbiomic profiles of bile in patients with benign and malignant pancreaticobiliary disease [pubmed](https://pubmed.ncbi.nlm.nih.gov/37071646/)

## 2022

- A targetable pathway in neutrophils mitigates both arterial and venous thrombosis [pubmed](https://pubmed.ncbi.nlm.nih.gov/36044595/)

- Transcription factors KLF15 and PPARδ cooperatively orchestrate genome-wide regulation of lipid metabolism in skeletal muscle [pubmed](https://pubmed.ncbi.nlm.nih.gov/35413288/)

## 2021

- Microbiome dysbiosis and epigenetic modulations in lung cancer: From pathogenesis to therapy [pubmed](https://pubmed.ncbi.nlm.nih.gov/34273520/)

- Germline EGFR variants are over-represented in adolescents and young adults (AYA) with adrenocortical carcinoma [pubmed](https://pubmed.ncbi.nlm.nih.gov/33326033/)

- The effect of oral Metronidazole on the vaginal microbiome of patients with recurrent bacterial vaginosis: A pilot investigational study	[doi](https://doi.org/10.1016/j.humic.2021.100081)

## 2020

- Comprehensive germline genomic profiles of children, adolescents and young adults with solid tumors	[pubmed](https://pubmed.ncbi.nlm.nih.gov/32371905/)

- Copy Number Variation and Clinical Outcomes in Patients With Germline PTEN Mutations [pubmed](https://pubmed.ncbi.nlm.nih.gov/32003824/)

- Exposure to Air Pollution Disrupts Circadian Rhythm through Alterations in Chromatin Dynamics	[pubmed](https://pubmed.ncbi.nlm.nih.gov/33241196/)

- Bacteriome and mycobiome and bacteriome-mycobiome interactions in head and neck squamous cell carcinoma	[pubmed](https://pubmed.ncbi.nlm.nih.gov/32637029/)

- Metabolic stress regulates genome-wide transcription in a PTEN-dependent manner	[pubmed](https://pubmed.ncbi.nlm.nih.gov/32744308/)

## 2019

- Microbiomes of Inflammatory Thoracic Aortic Aneurysms Due to Giant Cell Arteritis and Clinically Isolated Aortitis Differ From Those of Non-Inflammatory Aneurysms [pubmed](https://pubmed.ncbi.nlm.nih.gov/30993253/)

- PTEN modulates gene transcription by redistributing genome-wide RNA polymerase II occupancy	[pubmed](https://pubmed.ncbi.nlm.nih.gov/31127935/)

- Resveratrol-mediated glycemic regulation is blunted by curcumin and is associated to modulation of gut microbiota	[pubmed](https://pubmed.ncbi.nlm.nih.gov/31473511/)

- The Microbiome of Temporal Arteries	[pubmed](https://pubmed.ncbi.nlm.nih.gov/30993251/)

## 2018

- The microbiome in PTEN hamartoma tumor syndrome	[pubmed](https://pubmed.ncbi.nlm.nih.gov/29233840/)

## 2017

- Transfer of dysbiotic gut microbiota has beneficial effects on host liver metabolism	[pubmed](https://pubmed.ncbi.nlm.nih.gov/28302863/)

## 2016

- Microbial Culturomics to Map Halophilic Bacterium in Human Gut: Genome Sequence and Description of Oceanobacillus jeddahense sp. nov. [pubmed](https://pubmed.ncbi.nlm.nih.gov/27093109/)

- Periodontal dysbiosis linked to periodontitis is associated with cardiometabolic adaptation to high-fat diet in mice	[pubmed](https://pubmed.ncbi.nlm.nih.gov/27033119/)

## 2015

- Genome sequence and description of Pantoea septica strain FF5	[pubmed](https://pubmed.ncbi.nlm.nih.gov/26568786/)

- Noncontiguous finished genome sequence and description of Necropsobacter massiliensis sp. nov. [pubmed](https://pubmed.ncbi.nlm.nih.gov/26587237/)	

- High-quality genome sequence and description of Bacillus dielmoensis strain FF4T sp. nov.	[pubmed](https://pubmed.ncbi.nlm.nih.gov/26221422/)

## 2014

- Genome Sequence of Borrelia crocidurae Strain 03-02, a Clinical Isolate from Senegal [pubmed](https://pubmed.ncbi.nlm.nih.gov/25377717/)

- ARG-ANNOT, a New Bioinformatic Tool To Discover Antibiotic Resistance Genes in Bacterial Genomes [pubmed](https://pubmed.ncbi.nlm.nih.gov/24145532/)	

- Genome sequence and description of Corynebacterium ihumii sp. nov. [pubmed](https://pubmed.ncbi.nlm.nih.gov/25197488/)	

- High quality draft genome sequence and description of Occidentia massiliensis gen. nov., sp. nov., a new member of the family Rickettsiaceae	[pubmed](https://pubmed.ncbi.nlm.nih.gov/25780502/)

- Non-contiguous finished genome sequence and description of Paenibacillus gorillae sp. nov.	[pubmed](https://pubmed.ncbi.nlm.nih.gov/25197481/)

- Draft Genome Sequence of Necropsobacter rosorum Strain P709T [pubmed](https://pubmed.ncbi.nlm.nih.gov/25301642/)	

- Non-contiguous finished genome sequence and description of Collinsella massiliensis sp. nov. [pubmed](https://pubmed.ncbi.nlm.nih.gov/25197489/)	

- Non-contiguous finished genome sequence and description of Gorillibacterium massiliense gen. nov, sp. nov., a new member of the family Paenibacillaceae	[pubmed](https://pubmed.ncbi.nlm.nih.gov/25197465/)

- A polyphasic strategy incorporating genomic data for the taxonomic description of novel bacterial species. [pubmed](https://pubmed.ncbi.nlm.nih.gov/24505076/)

## 2013

- Non-contiguous finished genome sequence and description of Megasphaera massiliensis sp. nov. [pubmed](https://pubmed.ncbi.nlm.nih.gov/24501636/)

- Genomics and metagenomics in medical microbiology [pubmed](https://pubmed.ncbi.nlm.nih.gov/24200711/)

- Non-contiguous finished genome sequence and description of Clostridium dakarense sp. nov.	[pubmed](https://pubmed.ncbi.nlm.nih.gov/24501642/)

## 2008

- Exceptional molecular and coreceptor-requirement properties of molecular clones isolated from an Human Immunodeficiency Virus Type-1 subtype C infection	[pubmed](https://pubmed.ncbi.nlm.nih.gov/18328091/)

